//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("LoreSoft")]
[assembly: AssemblyProduct("SvnBackup")]
[assembly: AssemblyCopyright("Copyright (c) 2009 LoreSoft.")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.2")]
[assembly: AssemblyInformationalVersion("1.0.0.2")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCompany = "LoreSoft";
    
    internal const string AssemblyProduct = "SvnBackup";
    
    internal const string AssemblyCopyright = "Copyright (c) 2009 LoreSoft.";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyVersion = "1.0.0.0";
    
    internal const string AssemblyFileVersion = "1.0.0.2";
    
    internal const string AssemblyInformationalVersion = "1.0.0.2";
    
    private ThisAssembly() {
    }
}
